---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, inlcude=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
library(ggplot2)

data("ny_noaa")

noaa=
  ny_noaa %>% 
  janitor::clean_names() %>% 
  separate(date,into = c("year","month","day"),remove = FALSE,convert = TRUE) %>% 
mutate(
  tmax = as.numeric(tmax),
  tmin = as.numeric(tmin),
  prcp = prcp/10,
  tmax = tmax/10,
  tmin = tmin/10
)

```


Column {data-width=650}
-----------------------------------------------------------------------

### Graph 1: max temperature vs. min temperature of NYC temperature on Nov.1 from 1981 to 2010 

```{r}
  noaa %>% 
  filter(
    !is.na(tmin),
    !is.na(tmax),
    month == "11",
    day=="1"
  ) %>%
  mutate(text_label = str_c("ID:",id, "\nYear:", year,"\nPrecipitation:",prcp)) %>% 
plot_ly(x= ~tmin, y= ~tmax, type="scatter", mode="markers", color=~prcp,colors="viridis", text=~text_label)

```

Column {data-width=350}
-----------------------------------------------------------------------

### Graph 2: Distribution of max temperature 

```{r}
noaa %>% 
  mutate(
    monthname = case_when(
      month == 1 ~ "January",
      month == 2 ~ "February",
      month == 3 ~ "March",
      month == 4 ~ "April",
      month == 5 ~ "May",
      month == 6 ~ "June",
      month == 7 ~ "July",
      month == 8 ~ "August",
      month == 9 ~ "September",
      month == 10 ~"October",
      month == 11 ~"November",
      month == 12 ~"December"
    ),
    monthname= fct_reorder(monthname,month)
    ) %>% 
  plot_ly(x= ~ monthname,y= ~ tmax,type = "box", color = ~monthname, colors="viridis")
```

### Mean precipitation (mm) of every month from 1981 to 2010

```{r}
noaa %>% 
  mutate(
    monthname = case_when(
      month == 1 ~ "January",
      month == 2 ~ "February",
      month == 3 ~ "March",
      month == 4 ~ "April",
      month == 5 ~ "May",
      month == 6 ~ "June",
      month == 7 ~ "July",
      month == 8 ~ "August",
      month == 9 ~ "September",
      month == 10 ~"October",
      month == 11 ~"November",
      month == 12 ~"December"
    ),
    monthname= fct_reorder(monthname,month)
    ) %>% 
  group_by(monthname) %>% 
  summarize(prcp_mean = mean(prcp,na.rm = TRUE)) %>% 
  plot_ly(x = ~monthname, y=~prcp_mean,type="bar",color=~monthname, colors="viridis")
```



